snyk/snyk-python-plugin

plug/requirements/parser.py
test/inspect.test.js
test/workspaces/pip-app-trusted-host/requirements.txt

Ignores `--trusted-host` from requirements files.

fix: ignore trusted-host directive

---

.github/CONTRIBUTING.md
README.md
plug/requirements/LICENSE

chore: update readme for contributors

---

package.json
plug/requirements/parser.py
test/inspect.test.js
test/workspaces/pip-app-with-options/requirements.txt

before the fix it would try to parse it as requirement and raise an exception

fix: parser skips lines with options

---

plug/pip_resolve.py
test/inspect.test.js

as the backend doesn't need these anymore,
and it reduces the result json size by factor of ~3x

feat: don't include `from` arrays in tree

---

.travis.yml
README.md
dev-requirements.txt
lib/index.js
lib/sub-process.js
package.json
plug/pip_resolve.py
plug/pipfile.py
plug/pytoml/LICENSE
plug/pytoml/README.txt
plug/pytoml/__init__.py
plug/pytoml/core.py
plug/pytoml/parser.py
plug/pytoml/writer.py
plug/requirements/parser.py
plug/utils.py
test/inspect.test.js
test/test-utils.js
test/workspaces/pipenv-app/Pipfile
test/workspaces/pipenv-app/README
test/workspaces/pipfile-pipapp-pinned/Pipfile
test/workspaces/pipfile-pipapp-pinned/Pipfile.lock
test/workspaces/pipfile-pipapp-pinned/README
test/workspaces/pipfile-pipapp/Pipfile
test/workspaces/pipfile-pipapp/README

Adds initial, basic support for Python projects using `Pipfile` files for dependency management, specifically e.g. via `pipenv`.
The changes in `pip_resolve.py`, the new `pipfile.py` module, and `inspect.test.js`.
1. `npm test`
2. using `manual.js`
* The Pipfile parser I wrote is very basic and only extracts the info this plugin currently needs. This was the minimum needed to avoid depending on `pipenv`; it did require vendoring the `pytoml` library, though.
* I included a couple of "TODO" comments where ISTM that the code should be refactored, but I wanted to get some feedback first before making more extensive changes.
* The tests are now run in various separate virtualenvs. They are created as needed, assumed to be set up properly if they exist, and are reused between tests when …

feat: Pipfile (pipenv) initial support

---

test/inspect.test.js
test/test-utils.js

Fixes the test util `pipenvInstall()`.
`test/test-utils.js`
Run the test suite twice in succession.
This addresses test failures on PR #47.

test: fix the util pipenvInstall() crashing on missing Pipfile.lock

---

.travis.yml
test/inspect.test.js

I guess the deps for `irc` are floating and got outdated :(

chore: fix tests, upgrate Node.js version in Travis

---

.gitignore
README.md
setup.py
tox.ini

Current development documentation suggest dependencies are installed directly on the system without using a virtualenv, against a single python version. Both of these problems can be solved with `tox`.
`tox.ini`
Clone a fresh copy of the repo. Run `pip install tox`. Running `tox` will now handle dependency install and test running.
This process should work in or out of a virtualenv.
`tox` acts as a local replacement for the Travis CI build matrix, handling language and dependency installation.

chore: add tox config for local testing

---

plug/pip_resolve.py
test/inspect.test.js
test/workspaces/pip-app-deps-with-urls/requirements.txt

Checks for `name` attribute before calling replace in `resolve.py`
In new test.

fix: skip url defined dependencies

---

appveyor.yml
test/inspect.test.js
test/python-plugin.test.js
test/workspaces/pip-app-deps-conditional/requirements.txt
test/workspaces/pip-app-deps-editable/requirements.txt
test/workspaces/pip-app-deps-with-dashes/requirements.txt
tox.ini

Adding appveyor CI to python plugin. Few tests had to be adjusted in order to prevent compilation using C++ 14 which is not preset and doesn't bring any value. Therefore `{allowMissing: true}` was added occasionally.

chore: add appveyor.yml

---

lib/index.ts
plug/pip_resolve.py
test/inspect.test.js

When there are missing packages, actually display their names (for easier debugging).

fix: better error message when missing packages

---

.github/CODEOWNERS

Add boost as code owners, so every PR requires a review form the team too

chore: boost code owners

---

lib/index.ts
lib/sub-process.ts
package.json
tsconfig.json

Adds types to every function in the TS code; uses the common type definitions for plugins; converts some promise-based code to async/await.

refactor: add precise types to the TS code

---

lib/index.ts
package.json

Makes imports more compliant to common Node practices.

chore: use new style imports for CLI interface

---

pysrc/pip_resolve.py
test/inspect.test.js
test/workspaces/pip-app-with-python-markers/requirements.txt

Fixes a bug where we didn't pick up any dependency with Python version marker present.

fix: python version markers were not picked up

---

test/inspect-provenance.test.ts
test/inspect.test.js

Updates the latest changes for setup.py analysis to be compatible with the provenance changes.

fix: reconcile the conflicting changes for setup.py and provenance

---

package.json

bump CLI interface definition package version to ensure tap+ts-node compatibility

fix: bump CLI interface definition

---

README.md
lib/apply-remediation-implementation.ts
lib/index.ts
lib/inspect-implementation.ts
lib/types.ts
package.json
pysrc/README.md
test/build-args.test.js

Rearranges the code so that `index.ts` contains only top-level methods and the rest is extracted into -implementation.ts
Types are extracted to types.ts

chore: refactor code layout, document plugin methods

---

lib/inspect-implementation.ts
test/inspect.test.js
test/test-utils.ts

Add specific error for setup.py with missing deps and suggest `--allow-missing` if some deps are still found as missing.

feat: setup.py specific install command

---

test/workspaces/pipenv-app/Pipfile

Fix pipenv-app fix python version to 2.7
Failing builds because pipenv using python 3

fix: pipenv-app fix python version to 2.7

---

.circleci/config.yml

Upgrading Circle workflows to use matrix

chore: improve circle to use matrix directive

---

package.json

Bump snyk-poetry-lockfile-parser version to include handling circular dependencies

fix: bump poetry parse plugin

---

package.json
test/system/inspect.spec.ts

Includes fix to consider hyphens and underscores to be equivalent in package name comparisons

fix: bump snyk-poetry-lockfile-parser version

---

package.json

Includes fix to connect dependencies for repeated nodes for Poetry

fix: bump poetry parser version

---

.circleci/config.yml
README.md
lib/types.ts
test/system/inspect.spec.ts
test/system/inspect.test.js
test/test-utils.ts
test/workspaces/pip-app-with-options/requirements.txt
test/workspaces/pip-app-with-python-markers/requirements.txt
test/workspaces/pipenv-app/Pipfile

All the tests were failing since last September. This PR fixes all the broken tests and removed official support for pip9.0.

chore: fix broken tests and remove support for pip 9.0.3

---

.snyk
lib/dependencies/sub-process.ts
package.json

Escape child process arguments

fix: quote spawn args

---

.github/CODEOWNERS
package.json
test/system/inspect.spec.ts

since snyk-poetry-lockfile-parser@1.2.0 we're adding a "scope:dev/prod" label to every node

fix: fix tests

---

lib/dependencies/inspect-implementation.ts
pysrc/packaging/LICENSE
pysrc/packaging/LICENSE.APACHE
pysrc/packaging/LICENSE.BSD
pysrc/packaging/__about__.py
pysrc/packaging/__init__.py
pysrc/packaging/_compat.py
pysrc/packaging/_structures.py
pysrc/packaging/_typing.py
pysrc/packaging/markers.py
pysrc/packaging/requirements.py
pysrc/packaging/specifiers.py
pysrc/packaging/tags.py
pysrc/packaging/utils.py
pysrc/packaging/version.py
pysrc/pyparsing.py
pysrc/requirements/requirement.py

new versions of setuptools uses a newer version of "packaging" that doesn't support older ranges (i.e. 'pytz>dev') this vendor a previous version of the packages with breaking changes 
this change is inspired by https://github.com/snyk/snyk-python-plugin/pull/201

fix: fix new setuptools

---

pysrc/pip_resolve.py
test/fixtures/pipfile-without-dev-deps/Pipfile
test/unit/setup_file.spec.ts

today we fail in this scenario, more info here: https://snyksec.atlassian.net/browse/SUP-504

fix: support Pipfile without dev-packages when dev flag is set

---

lib/dependencies/sub-process.ts

If available restore system proxy settings before launching a subprocess. Similar to other plugins.

fix: restore system proxy

---

test/system/inspect.spec.ts

fix: fixed broken unit test

---

lib/dependencies/sub-process.ts
test/unit/sub-process.spec.ts

Fix changing a value that was passed by value.
added unit tests instead of manually testing.
HEAD-820

fix: changing global proxy setting as a side effect

---

.circleci/config.yml

fix: fix circleci config after introducing security scans

---

test/system/inspect.spec.ts

Updates the packages that are checked in tests to the latest versions (they get pulled in with the latest version as transitives).

fix: fix unit tests with latest versions of packages

---

pysrc/requirements/requirement.py

It fixes how we join local paths. The previous solution does not work for Windows local paths.

fix: fix join for local path

---

package.json
test/system/inspect.spec.ts

fix: update test
