lib/index.js
test/python-plugin.test.js

Double-dash arguments are now sent as an array of strings, split by spaces.
Supports older, string-string arguments as well, so no breaking change here.

feat: supporting args as an array

---

lib/index.js
plug/pip_resolve.py
test/inspect.test.js
test/python-plugin.test.js

passing `allowMissing: true` in the `options` argument to `inspect()`, will not raise an exception in case a required package is not installed.

feat: option to allow a requirement to be missing

---

plug/pip_resolve.py
test/inspect.test.js
test/workspaces/pip-app/requirements.txt

some packags like Django-Select2 install as lowercase, and the code
didn't expect that

fix: better handling of case sensetivity

---

plug/pip_resolve.py
test/inspect.test.js
test/workspaces/pip-app/requirements.txt

before this bugfix some packages like `jarico.text==1.9.2` and `testtools==2.3.0` caused an infinite recursion in the `pip_resolve.py`

fix: handle cyclic deps

---

plug/requirements/requirement.py
test/workspaces/pip-app-with-options/requirements.txt

until now it supported `--hashes`, but more exist e.g.:
https://pip.pypa.io/en/stable/reference/pip_install/#per-requirement-overrides
before the fix, `pip-resolve.py` would throw an exception if such a line
is encountered

fix: handle more per-requirements params

---

plug/requirements/fragment.py
test/workspaces/pip-app-deps-editable/requirements.txt

- prevents a crash when an editable fragment references a tag
- fragment parser was crashing on things like `#egg=simple==v1.0.0`
- note: removed the `-e` from the test fixture to force the issue

fix: prevent crash when editable fragment references a tag

---

lib/index.js
package.json
test/python-plugin.test.js

Adding assets to the binary release (by path.join(__dirname,PATH))
Dump all of the files to the disk (temp folder)
Execute the python script (pip_resolve.py) from the temp dir
This is the new behaviour of the plugin regarding if it run as binary \ not
No auto tests were added.
Manually tested "pkg ." (Zeit) with node 8 on the following os:
-Mac - python27
-Windows - python27 + python36
Trying to avoid creating a docker img for python, we realised it might be faster to use Zeit binary release as a proper solution

fix: add python files as Zeit assets, dump them to disk and run

---

test/manual.js

useful to run the plugin standalone, e.g.
```bash
$ cd <python-proj>
$ node <path to snyk-python-plugin>/test/manual.js requirements.txt
```

chore: add test/manual.js for manual invocation

---

.travis.yml

On Travis CI, add testing with various 3.x versions Python in addition to 2.7.
`.travis.yml` and the Travis build logs for this PR.
Trigger another Travis build.
This uses pyenv to install different versions of Python. pyenv comes pre-installed on Travis when using `dist: trusty` as we do in our `.travis.yml`. However, this version of pyenv is currently a bit old, and doesn't include the latest Python releases, e.g. 3.7.0, 3.6.6, 3.5.5 and 2.7.15. I've made a bit of extra effort here to use the latest available release of each _major.minor_ version of Python we'd like to test with.
On a different note, simply adding the following to `.travis.yml` doesn't work, unfortunately:
```yaml
python:
- "2.7"
- "3.5"
- "3.6"
```
It is also not possible to have Travis generate the Cartesian product …

test: test with multiple versions of Python

---

lib/index.js
plug/pip_resolve.py
test/inspect.test.js
test/python-plugin.test.js

Add support for testing dev dependencies via `snyk test --dev` in projects using pipenv.
`inspect()` in `index.js`, follow the new `isDevDeps` flag linearly through the code into `pip_resolve.py`.
Run `snyk test --dev` in Python projects using pipenv (`Pipfile`) and pip (`requirements.txt`), e.g. those in `test/workspaces`. It should successfully analyze the normal & dev dependencies for pipenv, and fail with an informative error for pip.
`Pipfile` natively has two separate sections for dependencies, `packages` and `dev-packages`. See [the docs](https://github.com/pypa/pipfile) for more info.
SC-5774

feat: support dev dependencies in pipenv projects

---

.travis.yml

Reducing the length of our CI test suite, as `python 3.6` provides sufficient coverage.

test: python 3.6 covers python 3.5 scenario, removing

---

.travis.yml
plug/pip_resolve.py
test/inspect.test.js

the `get_installed_distributions` method that was moved under `._internal`,
was moved again in pip 18 to `._internal.utils.misc`.
This PR tries the new location if the 2 existing options don't work.
Some `pipenv` tests here are failing with unrelated errors, these will be fixed in a consequent PR.

fix: support pip 18

---

plug/pip_resolve.py

Avoid importing `get_installed_distributions()` from inside pip.
To see why this is equivalent, see how we are currently calling `get_installed_distributions()` in `pip_resolve.py`, then read the (simple!) source of `get_installed_distributions()` [here](https://github.com/pypa/pip/blob/47b94f19bbe0167cebb92995fc52b80d41b5ba28/src/pip/_internal/utils/misc.py#L340).
`npm run test` (All tests pass!)

feat: just use pkg_resources rather than pip internals

---

plug/distPackage.py
plug/package.py
plug/reqPackage.py

this fails for users that don't have `pip` installed in the env, but this code is not used anyhow

fix: remove unsed render code & `import pip`

---

.gitignore
plug/pip_resolve.py
test/inspect.test.js
test/workspaces/pip-app-with-python-markers/requirements.txt
test/workspaces/pipfile-markers/Pipfile

Introduce filtering out deps based on current Python environment if they don't match based on their Python version markers
Run this locally on  https://github.com/lili2311/helios
- in plugin dir `npm link` 
- in the snyk CLI dir `npm link snyk-python-plugin` 
- clone https://github.com/lili2311/helios
- run a local `snyk-dev test` on helios, it should succeeded without any extra options
The plugin is not taking into account python version markers on dependencies and so we look for them when thy are not installed

test: Filter out deps that don't match required Python markers

---

.gitignore
pysrc/pip_resolve.py
pysrc/pipfile.py
pysrc/pytoml/README.txt
pysrc/pytoml/parser.py
pysrc/requirements/parser.py
pysrc/requirements/requirement.py
test/inspect.test.js
test/workspaces/pip-app/requirements.txt

Introduces an undocumented flag `--add-provenance`, which adds the provenance information to the top-level dependencies found by the Python plugin.

feat: optional provenance information for top-level dependencies

---

lib/index.ts
pysrc/pip_resolve.py
pysrc/setup_file.py
test/inspect.test.js
test/workspaces/setup_py-app/setup.py

Fixes #58 
Added specific support for setup.py in pip_resolve.py. 
The parsing logic is in setup_file.py
Here's what happens in the code:
It is simple enough. Dependencies in setup.py files are requirements.txt format compliant. Simply read these and act as if it is a requirements.txt file. Also read the `name` and `version` attributes from the setup.py.

Support setup.py files

---

.gitignore
lib/index.ts
package.json
pysrc/README.md
pysrc/pip_resolve.py
test/_setup.test.ts
test/fixtures/updated-manifests-with-constraints/constraints.txt
test/fixtures/updated-manifests-with-constraints/requirements.txt
test/fixtures/updated-manifests-with-python-markers/requirements.txt
test/fixtures/updated-manifests-without-constraints/requirements.txt
test/inspect-provenance.test.ts
test/inspect.test.js
test/remediation.test.ts
test/test-utils.ts
tsconfig-test.json
tsconfig.json

Adds exported function that applies updates to the manifest files.
This has to happen in the plugin, because that's where the manifests are parsed.
Currently would only used by Registry (via pip-deps, which creates the Python environment) to prepare fix PRs.
applyRemediationToManifests is the main entry point

feat: apply upgrade remediation to manifests

---

.travis.yml

I think that's the flag that allows Travis not to finish the entire matrix of builds if one of them fails, so the build queue will be freed up.

chore: enable early bailout for Travis builds

---

.npmrc

We don't use lockfiles for our libraries, as `npm install` doesn't consume anything other than the top-level lockfile anyway; this means the tests continuously run on new versions, which means we catch issues before they affect customers (hopefully).
The lockfile is current in the `.gitignore`, but may still be generated locally, so this patch adds a `.npmrc` flag to prevent this.

chore: Prevent lockfile generation

---

package.json
pysrc/pip_resolve.py
pysrc/test_pip_resolve.py

fixes an issue where lines like `enum34==1.1.6 ; python_version == '2.*'` were not supported

fix: match python_version with wildcards (e.g. "2.*")

---

dev-requirements.txt
package.json
pysrc/pip_resolve.py
pysrc/test_pip_resolve.py

This is a triage fix for Zendesk #1672 and #1817. Supporting Environment Markers with expressions like:
```
futures==3.2.0; python_version == '2.6' or python_version >= "2.7"
```

fix: Support 'or' operators in marker expressions

---

pysrc/pip_resolve.py
pysrc/test_pip_resolve.py

I took a stab at fixing #85.
I also added unit tests.
Someone with more knowledge of how snyk handles dependency graphs for python should take a look. I only solved my immediate problem, but the new `canonicalize_package_name(name)` method could (and should) probably be used in other places.
1) Look at #85.
2) Read https://packaging.python.org/guides/distributing-packages-using-setuptools/#name
3) Look at the unit tests I added.
Setup a Pipfile that references a package with a hyphon in the name, but where the package displays a period when you do a pip freeze.
(I would provide an example, but I ran into this problem on internal projects.)
Found this problem while evaluating Snyk. I have a meeting with 
`elisabeth@snyk.io` tomorrow morning. Helping get these (and other) issues fixed …

Adding python package name canonicalization.

---

lib/inspect-implementation.ts
test/inspect-provenance.test.ts
test/inspect.test.js

Add return `targetFile` from plugin `setup.py` if it's the project manifest

feat: support setup.py as a return target file

---

.circleci/config.yml

Node 6 doesn't include a version of npm that bundles npx, so we build with 8. Everything is still tested (including the build) under node 6 from the test flow, so it should be okay.

fix: Correct the release process in CircleCI

---

lib/requirements-file-parser.ts
test/remediation.spec.ts

The new requirements parser and tests were only matching single digits in version strings, such as `2.0.1`, which falls over very quickly, for example when faced with `flask==0.12.1`.
This patch fixes the parser, and adds a test

fix: Match multiple digits in package versions

---

lib/index.ts
lib/requirements-file-parser.ts
lib/update-dependencies/requirements/index.ts
test/remediation.spec.ts

Based on: https://github.com/snyk/snyk-python-plugin/pull/98/files
https://github.com/snyk/snyk-python-plugin/pull/99/commits/984c6a6289376a9dfa5892f247c3ef62237186e5
New file types will require very different handling anyway
So will fixing multiple files together at that stage this should be refactored or a separate new function will be created.

fix: use file contents to update deps not a file object (support for custom named manifests)

---

.circleci/config.yml

Fix release by using required node version for semantic release

fix: use node 10 for release

---

README.md
jest.config.js
lib/dependencies/index.ts
lib/dependencies/inspect-implementation.ts
lib/dependencies/poetry.ts
lib/types.ts
package.json
test/matchers/dep-graph.ts
test/matchers/setup.ts
test/system/inspect-provenance.test.ts
test/system/inspect.spec.ts
test/system/inspect.test.js
test/test-utils.ts
test/tsconfig.json
test/unit/build-args.spec.ts
test/unit/poetry.spec.ts
test/workspaces/poetry-app-without-lockfile/pyproject.toml
test/workspaces/poetry-app/poetry.lock
test/workspaces/poetry-app/pyproject.toml
tsconfig-test.json

Detect poetry being used when target file is 'pyproject.toml' (poetry manifest).
Use snyk-poetry-lockfile-parser to return dep-graph.
Updated typescript and eslint devDependencies to fix lint.
Added custom dep-graph jest matcher to compare dep-graphs.
Moved tests into either 'unit' or 'system' and refactor setup to be
script (not tap test) that runs before all tests.
Downgrade jest-diff version used as seems incompatible with node8.

feat: add poetry support

---

package.json

Bump snyk-poetry-lockfile-parser version to include auto-resolving dependencies with underscores to hyphens

fix: bump poetry parser plugin 

---

package.json

Bumps the poetry parser version to include the following fixes:
- Stop parser from trying to look up packages not propagated to the lockfile (wheel, distributed, pip,  setuptools)
- Stop parser from failing when failing to locate dependency in lockfile and instead log a warning. This could be because of python requirements allowing it in the manifest but not actually installing it and adding a lockfile entry or because of how Poetry treats the use of underscores and hyphens when installing packages
- Reversed PR that introduced swapping underscores in manifest for hyphens in lockfile. This was due to a misunderstanding of how Poetry worked and is remediated by the above.
[LOKI-174](https://snyksec.atlassian.net/browse/LOKI-174)
[LOKI-175](https://snyksec.atlassian.net/browse/LOKI-175) …

fix: bump poetry parser version to include multiple fixes

---

.circleci/config.yml

These CI contexts aren't actually needed to pull in any deps, so lets just remove them

fix: Remove unneccessary CI contexts

---

pysrc/pip_resolve.py

This is to fix a bug where we flag multiple licenses for the same node due to case sensitivity
This is to fix a bug where we flag multiple licenses for the same node due to case sensitivity
Example: 
If we have `django` (lowercase) as a direct dependency in a project with `Django` as a transitive dependency they will be treated as separate packages.

fix: make transitive deps lowercase

---

lib/dependencies/index.ts
lib/dependencies/inspect-implementation.ts
test/system/inspect.test.js
test/workspaces/pipfile-nested-dirs/README
test/workspaces/pipfile-nested-dirs/nested/directory/Pipfile

Changes the root and targetFile when scanning a Pipfile to ensure that Pipenv behaves properly
Now if given --file=foo/bar/Pipfile the root is changed to $pwd/foo/bar and targetFile to Pipfile
Given how the subprocess is spawned, this now ensure that the pipenv command is run in the directory
containing the pipfile instead of outside.
An alternative would be to set PIPENV_PIPFILE env variable with the path to Pipfile but this has the
added benefit of letting Pipenv run how it assumes it should be: in a directory with a Pipfile or
a sub directory of one containing, not above a Pipfile
This method also preserves the original behavior of scanning the Pipfile in $cwd because in that
case the path.dirname(targetFile) is the same as root, and path.basename(targetFile) is the same
as targetFile …

fix: support --file (and --all-projects) for Pipfile (133)

---

lib/dependencies/index.ts
lib/dependencies/inspect-implementation.ts
lib/dependencies/poetry.ts
test/system/inspect.spec.ts
test/unit/poetry.spec.ts

As a part of this PR we we will pass `poetry.lock` file to this plugin as opposed to `pyproject.toml`. This is because `pyproject.toml` is not a reliable manifest file (see https://github.com/snyk/snyk/issues/1802) and therefore we need to use `poetry.lock` as a traget file. This is a breaking change 
New published version has to be integrated into https://github.com/snyk/snyk/pull/1879
1. checkout this branch https://github.com/snyk/snyk/pull/1879
2. link snyk-python-plugin to snyk repo - make sure you are using the same node versions in both repos
3. run tests in https://github.com/snyk/snyk/pull/1879
[LOKI-280](https://snyksec.atlassian.net/browse/LOKI-280)

fix: use poetry-lock file as a target file for poetry project

---

lib/dependencies/inspect-implementation.ts
test/fixtures/pipenv-project/Pipfile
test/fixtures/poetry-project/poetry.lock
test/fixtures/poetry-project/pyproject.toml
test/fixtures/setuptools-project/setup.py
test/system/inspect-provenance.test.ts
test/system/inspect.spec.ts

This pr fixes the bug that returned poetry.lock as the target file. The pr corrects this by returning pyproject.toml as the target file. 
The problem is that target file is a part of project uniqueness constraint. This means that if target file for a project changes, our system behaves as if it received completely new project. This creates duplicate projects and diverges the project monitor history from original (pyproject.toml) to new one (poetry.lock).
https://snyksec.atlassian.net/jira/software/projects/LOKI/boards/176?selectedIssue=LOKI-355
First image shows the target file received before the change. 
The second image shows the target file after the change.

fix: bug - selected target file for poetry in python plugin 

---

lib/dependencies/inspect-implementation.ts
lib/errors.ts
lib/index.ts
test/system/inspect.spec.ts

Improve some error messaging in the plugin. Make sure to export the definitions. The idea is that consumers of a package (such as `pip-deps`) will be able to recognise more specific errors and act on them.

feat: improve error message for pip manifests failures

---

.gitignore
lib/dependencies/build-dep-graph.ts
lib/dependencies/index.ts
lib/dependencies/inspect-implementation.ts
package.json
pysrc/pip_resolve.py
test/fixtures/dence-dep-graph/expected.json
test/fixtures/dence-dep-graph/pip_resolve_output.json
test/system/inspect-provenance.test.ts
test/system/inspect.spec.ts
test/system/inspect.test.js

this change will return a depgraph instead of a deptree from the plugin

feat: return depgraph from plugin

---

.gitignore
lib/dependencies/build-dep-graph.ts
lib/dependencies/index.ts
lib/dependencies/inspect-implementation.ts
test/system/inspect.spec.ts

when we used deptree, one could easily override the dep-tree's name with updating the name property.
in dep-graph this is not possible, so we need a way to override this.

feat: add option "projectName" flag to customize root node and package name

---

lib/dependencies/poetry.ts

Even if the error is a string and not an object
We observed an error that was just a string (probably coming from a call like `throw 'some error'` that was swallowed as an `undefined`
```
Monitoring /project...
Error processing poetry project. undefined
at monitor (/snapshot/snyk/dist/cli/webpack:/snyk/src/cli/commands/monitor/index.ts:292:9)
at runCommand (/snapshot/snyk/dist/cli/webpack:/snyk/src/cli/index.ts:58:25)
at main (/snapshot/snyk/dist/cli/webpack:/snyk/src/cli/index.ts:316:4)
```
In this case, it was `python: not found`

fix(poetry): capture error message

---

pysrc/pip_resolve.py
test/system/inspect.test.js
test/workspaces/pip-app-with-repeating-dependency/requirements.txt

In https://github.com/snyk/snyk-python-plugin/pull/159 we introduced a change to use dep graph instead of dep tree
In specific scenarios, we see a direct dependency more than once for a specific package.
This change will make sure we're setting it correctly

fix: fix 'key psutil not found in packageToDepTreeMap' error

---

pysrc/pip_resolve.py

Previously the regex used "=>" whereas pep508 specifies ">=" as the ge
comparator. https://www.python.org/dev/peps/pep-0508/#environment-markers

fix: use correct requirements filter regex for 'ge'

---

lib/dependencies/index.ts
lib/dependencies/inspect-implementation.ts
pysrc/pip_resolve.py
test/unit/build-args.spec.ts

this change introduce "--allow-empty" flag, that doesn't throw "No dependencies found." error when manifest is empty.

feat: allow empty manifest flag

---

.circleci/config.yml
pysrc/requirements/parser.py

today we fail for the following requirements line "-r req-something.txt # some comment" because of the way we split the line
this change will just take the second item in the line (right after the '-r' flag)
in addition, this will fix the release phase on circle

fix: when a line inside "requirements.txt" has more than one space

---

pysrc/pip_resolve.py

Since the last change of introducing packageToDepTreeMap, we're seeing some errors in logs of "key XXX not found in packageToDepTreeMap"
This happens because current implementation ignores "extras" property (i.e. requests['security']) and identify duplicate "requests" children.
this small change doesn't add support for "extras" property, but simply ignores it in a more graceful way (no regression here)

fix: fix key XXX not found in packageToDepTreeMap

---

pysrc/pip_resolve.py

This PR supports the special case when in a Pipfile there is no `[packages]` section.

fix: support pipenv empty packages

---

pysrc/setup_file.py
test/unit/setup_file.spec.ts

today we only support "from setuptools import setup; setup(...)", this change adds support for "import setuptools; setuptools.setup(...)"

fix: support another kind of setuptools import

---

pysrc/pipfile.py
pysrc/test_pipfile.py

The pipfile parser was buggy because the toml parser returns both the value of the attribute and the end position as a tuple, but we only need the value. This changes fix that.
You can see in the support ticket that snyk-python-plugin fails for a Pipfile that has markers, because the regex function does not receive a string, but the tuple mentioned above.
[JIRA ticket SUP-1872](https://snyksec.atlassian.net/browse/SUP-1872)

fix: [SUP-1872] fixed pipfile parser

---

lib/dependencies/inspect-implementation.ts
test/system/inspect.spec.ts

On some Linux OS systems, 'python' command does not exist without alias to 'python3', so this is a fix to use the given command to verify version and install setuptools, instead of just using python/

fix: use correct python command

---

pysrc/pip_resolve.py
test/system/inspect.spec.ts
test/workspaces/pip-app-deps-canonicalization/requirements.txt

A bunch of projects were failing with `Required packages missing: <package_name>`. This was happening due to some symbol `-`, `_`, `.` miss-matching in the package names. The solution is to canonicalize the package names before comparing them.

fix: package missing error

---

pysrc/pip_resolve.py
test/system/inspect.spec.ts
test/workspaces/pip-app-circular-deps/requirements.txt

Some python packages, have circular dependencies. For example `apache-airflow` requires `apache-airflow-providers-common-io` which requires `apache-airflow`. This behaviour results in a recursion error:  
**RecursionError: maximum recursion depth exceeded while calling a Python object.**
This fix makes sure that if a dependency was already analysed, it won't get analysed again, thus avoiding the recursion error
This bug was introduced after fixing another [issue](https://github.com/snyk/snyk-python-plugin/pull/231)
[Slack conversation](https://snyk.slack.com/archives/CFTAUCYQ7/p1706869951896279)

fix: python circular deps / recursion error

---

lib/dependencies/index.ts
lib/dependencies/inspect-implementation.ts
test/system/inspect.spec.ts
test/test-utils.ts

After https://github.com/snyk/snyk-python-plugin/pull/242.
Fixed command to check python version. For pipenv projects, it changes to `pipenv`, but we need the initial `python` or `python3` to check python version with `--version`.
Python version is checked because setuptools need to be installed in case of python 3.12.
Added tests to simulate pipenv virtualenv, where pipenv install is performed and then inspect called.

fix: correct cmd to get python version for pipenv projects

---

lib/dependencies/index.ts
lib/dependencies/inspect-implementation.ts
pysrc/pip_resolve.py
test/system/inspect.spec.ts

Removes setuptools installation for python 3.12. setuptools is only needed for setup.py files tests, case in which it will actually be installed on the client's machine. 
Moved imports for setup file only where it's the case to use them.

fix: removed setuptools installation on the plugin

---

lib/dependencies/inspect-implementation.ts
lib/errors.ts
pysrc/constants.py
pysrc/pip_resolve.py
pysrc/requirements/parser.py
test/system/inspect.spec.ts
test/workspaces/pip-app-local-nonexistent-file/lib/nonexistent/not-setup-file.txt
test/workspaces/pip-app-local-nonexistent-file/requirements.txt

Handles errors for a requirement line that can't be parsed.
If --skip-unresolved (allowMissing) is true, the lines that throw errors are ignored.

fix: [OSM-2206] skip unresolved local packages

---

pysrc/pip_resolve.py
pysrc/test_pip_resolve_py3.py

- Refactors regex used to select the `sys_platform`
- Improved logic to support multiple `sys_platform`

fix: [OSM-2189] refactor sys_platform selector

---

test/system/inspect.spec.ts

Remove checked version for sub-dependency in unit tests because newer python versiones bring in the sub-dependency with a later version. For this specific test, we are not concerned with what version the sub-dependency gets pinned at.

chore: remove checked dependency version from unit test
